name: Deploy Frontend to EC2

on:
  push:
    branches:
      - fix/audio-issue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/recruit-inn-fe
          git pull origin fix/audio-issue
          npm install
          npm run build
          pm2 restart 1
          pm2 save
